name: Docker Image Deployment to Azure Web App

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

env:
  DOCKER_IMAGE_NAME: "service-documents"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build ./backend/services/service-documents --file Dockerfile --tag "${{ env.DOCKER_IMAGE_NAME }}:latest"
      - name: Docker Login
        run: docker login --username '${{secrets.DOCKER_LOGIN}}' --password '${{secrets.DOCKER_PASSWORD}}'
      - name: Tag the Dcoker image
        run: docker tag '${{env.DOCKER_IMAGE_NAME}}':latest '${{secrets.DOCKER_LOGIN}}'/'${{env.DOCKER_IMAGE_NAME}}':latest
      - name: Push the Docker image
        run: docker push '${{secrets.DOCKER_LOGIN}}'/'${{env.DOCKER_IMAGE_NAME}}':latest
